### ISSUE TITLE
Unique p2p offer id (createExternalOrder)

### ISSUE THREAD

**Issue by chancity** [kinecosystem/marketplace-server#169]
I'm curious, are unique p2p offer ids intended or an oversight?   kin-devplatform-marketplace-server is also designed this way.

https://github.com/kinecosystem/marketplace-server/blob/master/scripts/src/public/services/orders.ts#L244-L246

https://github.com/kinecosystem/kin-devplatform-marketplace-server/blob/master/scripts/src/public/services/orders.ts#L150-L152

**Comment by nitzantomer** [comment]
The ids are intended to be unique.
The idea is that it will give the digital service/application an easy way to identify its offers. The order id is the identifier for a specific instance of a used offer.
We are aware of the possible need for reusing the offer id (i.e.: an offer a user may use more than once), and we will solve it in a different method (we already have something in mind), but the need just hasn't presented itself yet.

Do you need to do that? What is your scenario?

**Comment by nitzantomer** [comment]
@chancity ^^

**Comment by chancity** [comment]
Currently I'm creating pay_to_user offers.  I went ahead with appending an identifer to a base offer id.  What prompted me to ask this question were these lines of code below.  The query string filter with an optional offerid.

export async function getOrderHistory(
	userId: string,
	filters: { origin?: db.OrderOrigin; offerId?: string; },

**Comment by chancity** [comment]
Also why is this a thing?  Why does the API not allow you to view an order that is open?

export async function getOrder(orderId: string, userId: string, logger: LoggerInstance): Promise<Order> {
	const order = await db.Order.getOne(orderId, "!opened") as db.MarketplaceOrder | db.ExternalOrder;

**Comment by nitzantomer** [comment]
@chancity 
Well, open orders (orders with status `opened`) aren't meant to be handled by the clients, they only live in the context of the server.
Clients (in our design) should only handle orders which are `pending`, `completed` or `failed`.

As for the why, basically because of what you went through.
A client may open an order and then not go through with it,  for a verity of reasons.
You can see that when creating a new order (based on an offer id) the client will receive the existing open order if one already exists for this offer id.

An order only becomes "permanent" (for the client) once it has been submitted (and turned into `pending`).

**Comment by chancity** [comment]
That makes sense now, thanks.
